### ISSUE TITLE
A rare bug

### ISSUE THREAD

**Issue by MrBlasyMSK** [brokiem/Trashcan#1]
https://streamable.com/sbbmu2

No + plugins
PHP: 8.0.16
Pocketmine: 4.2.3
OS: linux

(dev#9)
Edit: still in dev14

**Comment by brokiem** [comment]
This is [InvMenu](https://github.com/Muqsit/InvMenu) bug, i think its caused by server <-> player latency

**Comment by MrBlasyMSK** [comment]
Thx, im gonna rep it

**Comment by MrBlasyMSK** [comment]
@brokiem Muqsit said that the bug is fixed by installing [InvCrashFix](https://github.com/Muqsit/InvCrashFix/tree/api-4.0)
It would be nice if the plugin could integrate it by default so that it doesn't happen to more people.
